import Head from 'next/head'
import Link from 'next/link'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Vishnu App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to Next.js!
        </h1><hr/>

        <Link href='/about'>About - custom Layout Demo</Link><br/>
        <Link href='/image'>Image Demo</Link><br/>
        <Link href='/news'>News : preview Demo</Link><br/>


        
      </main>

      
    </div>
  )
}
